-- =============================================================================
-- V1 — Initial schema
-- =============================================================================
-- Baseline for the NEVOLYN Technology backend. Mirrors the JPA entities in
-- com.nevolyn.model exactly; production runs with
-- spring.jpa.hibernate.ddl-auto=validate, so any drift between these tables and
-- those entities fails the application at startup rather than silently
-- corrupting live data.
--
-- Migrations are immutable once applied. Flyway records a checksum per file and
-- refuses to start if an already-applied file changes. To alter the schema, add
-- V2__<description>.sql — never edit this one.
--
-- Column names use snake_case because Spring Boot's default
-- CamelCaseToUnderscoresNamingStrategy maps e.g. inquiryId -> inquiry_id.
--
-- Scope: this database stores visitor submissions only. Static site content —
-- the team roster, innovations, milestones and news — lives in
-- frontend/lib/data/ and ships with the frontend build. Do not add tables for it.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- contact_inquiries — visitor messages from the homepage contact form
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contact_inquiries (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Public reference shown to the visitor, e.g. INQ-2026-0042. Unique so a
    -- generated collision fails loudly at insert instead of confusing support.
    inquiry_id         VARCHAR(64)  NOT NULL UNIQUE,

    name               VARCHAR(100) NOT NULL,
    email              VARCHAR(150) NOT NULL,
    subject            VARCHAR(200) NOT NULL,
    message            TEXT         NOT NULL,

    -- Single-use token from the step-1 verification email. Nullable because it
    -- is cleared conceptually once consumed, and absent for discarded rows.
    verification_token VARCHAR(64),

    -- False until the sender proves ownership of the address. Unverified rows
    -- are never forwarded to the R&D team.
    is_verified        BOOLEAN      NOT NULL DEFAULT FALSE,
    verified_at        TIMESTAMP,

    created_at         TIMESTAMP    NOT NULL
);

-- Token lookup runs on every click of a verification link.
CREATE INDEX IF NOT EXISTS idx_contact_inquiries_verification_token ON contact_inquiries (verification_token);

-- -----------------------------------------------------------------------------
-- job_applications — careers submissions, with an uploaded CV
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS job_applications (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Public reference shown to the candidate, e.g. APP-2026-0042.
    application_id     VARCHAR(64)  NOT NULL UNIQUE,

    name               VARCHAR(100) NOT NULL,
    email              VARCHAR(150) NOT NULL,
    phone              VARCHAR(30)  NOT NULL,
    address            VARCHAR(250) NOT NULL,
    reason             TEXT         NOT NULL,

    linkedin           VARCHAR(255),
    github             VARCHAR(255),
    website            VARCHAR(255),

    -- Absolute path on the container filesystem. NOTE: that filesystem is
    -- ephemeral on Render's free tier, so this path can outlive the file it
    -- points at. The CV is also emailed to the admin on verification.
    resume_path        VARCHAR(500) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,

    verification_token VARCHAR(64),
    is_verified        BOOLEAN      NOT NULL DEFAULT FALSE,
    verified_at        TIMESTAMP,

    created_at         TIMESTAMP    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_job_applications_verification_token ON job_applications (verification_token);
