-- =============================================================================
-- V1 - job_applications (Endpoint: POST /api/v1/applications)
--
-- Optimal, production-grade schema for NEVOLYN Careers & Join Us applications.
-- Stores applicant credentials, statement of motivation, professional links,
-- CV document metadata, verification state, acknowledgement state,
-- and recruitment selection outcome.
-- =============================================================================

CREATE TABLE IF NOT EXISTS job_applications
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Public reference code shown to candidate (e.g. APP-2026-X8K2M9PQ)
    application_id     VARCHAR(64)  NOT NULL UNIQUE,

    -- Applicant input details
    name               VARCHAR(100) NOT NULL,
    email              VARCHAR(150) NOT NULL,
    phone              VARCHAR(30)  NOT NULL,
    address            VARCHAR(250) NOT NULL,
    reason             TEXT         NOT NULL,

    -- Professional profile links
    linkedin           VARCHAR(255),
    github             VARCHAR(255),
    website            VARCHAR(255),

    -- CV upload document metadata and merged dossier
    resume_path        VARCHAR(500) NOT NULL,
    dossier_path       VARCHAR(500),
    original_file_name VARCHAR(255) NOT NULL,
    file_size_bytes    BIGINT,
    file_content_type  VARCHAR(100),

    -- Verification pipeline
    verification_token VARCHAR(64),
    is_verified        BOOLEAN      NOT NULL DEFAULT FALSE,
    verified_at        TIMESTAMP,

    -- Lifecycle & Acknowledgement (when applied & when acknowledged)
    is_acknowledged    BOOLEAN      NOT NULL DEFAULT FALSE,
    acknowledged_at    TIMESTAMP,
    created_at         TIMESTAMP    NOT NULL,

    -- Selection outcome (whether selected or not)
    is_selected        BOOLEAN      NOT NULL DEFAULT FALSE,
    selection_status   VARCHAR(32)  DEFAULT 'PENDING',
    selected_at        TIMESTAMP,
    review_notes       TEXT
);

CREATE INDEX IF NOT EXISTS idx_job_applications_app_id
    ON job_applications (application_id);

CREATE INDEX IF NOT EXISTS idx_job_applications_verification_token
    ON job_applications (verification_token);

CREATE INDEX IF NOT EXISTS idx_job_applications_acknowledged
    ON job_applications (is_acknowledged, acknowledged_at);

CREATE INDEX IF NOT EXISTS idx_job_applications_selection
    ON job_applications (is_selected, selection_status);

CREATE INDEX IF NOT EXISTS idx_job_applications_created
    ON job_applications (created_at DESC);
