-- =============================================================================
-- V2 - contact_inquiries (Endpoint: POST /api/v1/contact)
--
-- Optimal, production-grade schema for visitor contact inquiries submitted
-- through the NEVOLYN homepage contact form.
-- Stores visitor message credentials, verification state, and acknowledgement.
-- =============================================================================

CREATE TABLE IF NOT EXISTS contact_inquiries
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Public reference code shown to visitor (e.g. INQ-2026-X8K2M9PQ)
    inquiry_id         VARCHAR(64)  NOT NULL UNIQUE,

    -- Submitter input details
    name               VARCHAR(100) NOT NULL,
    email              VARCHAR(150) NOT NULL,
    subject            VARCHAR(200) NOT NULL,
    message            TEXT         NOT NULL,

    -- Verification pipeline
    verification_token VARCHAR(64),
    is_verified        BOOLEAN      NOT NULL DEFAULT FALSE,
    verified_at        TIMESTAMP,

    -- Lifecycle & Acknowledgement (when submitted & when acknowledged)
    is_acknowledged    BOOLEAN      NOT NULL DEFAULT FALSE,
    acknowledged_at    TIMESTAMP,
    status             VARCHAR(32)  NOT NULL DEFAULT 'NEW',
    created_at         TIMESTAMP    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_contact_inquiries_inquiry_id
    ON contact_inquiries (inquiry_id);

CREATE INDEX IF NOT EXISTS idx_contact_inquiries_verification_token
    ON contact_inquiries (verification_token);

CREATE INDEX IF NOT EXISTS idx_contact_inquiries_acknowledged
    ON contact_inquiries (is_acknowledged, acknowledged_at);

CREATE INDEX IF NOT EXISTS idx_contact_inquiries_status
    ON contact_inquiries (status);

CREATE INDEX IF NOT EXISTS idx_contact_inquiries_created
    ON contact_inquiries (created_at DESC);
