/**
 * SEO & Entity Graph Configuration for NEVOLYN Technology
 *
 * Defines the core brand identity, metadata defaults, exhaustive brand keywords,
 * typo variations, Bengali transliterations, and counterpart entity relationships
 * for NEVOLYN as the parent engineering and deep-tech company.
 *
 * @module lib/seo/config
 */

/** Comprehensive list of English and Bengali brand aliases, phonetic variations, and common typo spellings */
export const NEVOLYN_BRAND_ALIASES = [
  // ── Canonical English & Standard Variations ──
  'NEVOLYN',
  'Nevolyn',
  'nevolyn',
  'NEVOLYN Technology',
  'Nevolyn Technology',
  'nevolyn technology',
  'NEVOLYN Technologies',
  'Nevolyn Technologies',
  'nevolyn technologies',
  'NEVOLYN Tech',
  'Nevolyn Tech',
  'nevolyn tech',
  'NEVOLYN Automation',
  'Nevolyn Automation',
  'nevolyn automation',
  'NEVOLYN Bangladesh',
  'Nevolyn Bangladesh',
  'nevolyn bangladesh',
  'NEVOLYN Official',
  'Nevolyn Official',
  'nevolyn official',
  'nevolyn.com',
  'www.nevolyn.com',

  // ── Bengali Script Spellings & Variations ──
  'নেভোলিন',
  'নেভোলিন টেকনোলজি',
  'নেভোলিন অটোমেশন',
  'নেভোলিন বাংলাদেশ',
  'নেভোলিন টেক',
  'নেভলিন',
  'নেভলিন টেকনোলজি',
  'নেভলিন অটোমেশন',
  'নেভলিন বাংলাদেশ',
  'নেভোলীন',
  'নেভোলীন টেকনোলজি',
  'নেভোলীন অটোমেশন',
  'নেভলীন',
  'নেভলীন টেকনোলজি',
  'নেভালিন',
  'নেভালিন টেকনোলজি',
  'নেভালিন অটোমেশন',
  'নেভ্যালিন',
  'নেভ্যালিন টেকনোলজি',
  'নেভোলাইন',
  'নেভোলাইন টেকনোলজি',
  'নেভোলিন্',
  'নেভোলিন কোম্পানি',
  'নেভোলিন লিমিটেড',

  // ── Bengali Phonetic B-transliterations (ব/v phonetic interchange) ──
  'নেবোলিন',
  'নেবোলিন টেকনোলজি',
  'নেবোলিন অটোমেশন',
  'নেবোলিন বাংলাদেশ',
  'নেবলিন',
  'নেবলিন টেকনোলজি',
  'নেবলিন অটোমেশন',
  'নেবোলীন',
  'নেবোলীন টেকনোলজি',
  'নেবালিন',
  'নেবালিন টেকনোলজি',
  'নিভোলিন',
  'নিভোলিন টেকনোলজি',
  'নিভলিন',
  'নিভলিন টেকনোলজি',

  // ── English Phonetic Vowel & Spelling Variations (i for y, dropped vowels) ──
  'Nevolin',
  'nevolin',
  'NEVOLIN',
  'Nevolin Technology',
  'nevolin technology',
  'Nevolin Automation',
  'nevolin automation',
  'Nevolin Bangladesh',
  'Nevlyn',
  'nevlyn',
  'NEVLYN',
  'Nevlyn Technology',
  'Nevlyn Automation',
  'Nevlin',
  'nevlin',
  'NEVLIN',
  'Nevlin Technology',
  'Nevlin Automation',
  'Nevalyn',
  'nevalyn',
  'NEVALYN',
  'Nevalyn Technology',
  'Nevalin',
  'nevalin',
  'NEVALIN',
  'Nevalin Technology',
  'Nevelyn',
  'nevelyn',
  'NEVELYN',
  'Nevelyn Technology',
  'Nevelin',
  'nevelin',
  'NEVELIN',
  'Nevelin Technology',
  'Nevoleen',
  'nevoleen',
  'NEVOLEEN',
  'Nevleen',
  'nevleen',
  'Nevlyne',
  'nevlyne',
  'Nevline',
  'nevline',

  // ── English South Asian B/W Phonetic Substitutions ──
  'Nebolyn',
  'nebolyn',
  'NEBOLYN',
  'Nebolyn Technology',
  'Nebolyn Automation',
  'Nebolin',
  'nebolin',
  'NEBOLIN',
  'Nebolin Technology',
  'Nebolin Automation',
  'Neblyn',
  'neblyn',
  'NEBLYN',
  'Neblin',
  'neblin',
  'NEBLIN',
  'Neblyn Technology',
  'Nebalyn',
  'nebalyn',
  'NEBALYN',
  'Nebalin',
  'nebalin',
  'NEBALIN',
  'Newolyn',
  'newolyn',
  'NEWOLYN',
  'Newolin',
  'newolin',
  'NEWOLIN',
  'Newlyn',
  'newlyn',

  // ── Common Keyboard Typos, Swaps & Transpositions ──
  'Neovlyn',
  'neovlyn',
  'NEOVLYN',
  'Neovlin',
  'neovlin',
  'Nevloyn',
  'nevloyn',
  'Nevloyn Technology',
  'Nevoyln',
  'nevoyln',
  'Nevolny',
  'nevolny',
  'Nevlon',
  'nevlon',
  'NEVLON',
  'Nevlon Technology',
  'Nevolynn',
  'nevolynn',
  'NEVOLYNN',
  'Nevvolyn',
  'nevvolyn',
  'Nevoly',
  'nevoly',
  'Nivolyn',
  'nivolyn',
  'NIVOLYN',
  'Nivolin',
  'nivolin',
  'NIVOLIN',
  'Navolyn',
  'navolyn',
  'Navolin',
  'navolin',
] as const

/** Legitimate official brand aliases for Schema.org structured data */
export const NEVOLYN_LEGITIMATE_ALIASES = [
  'Nevolyn',
  'NEVOLYN Technology',
  'Nevolyn Technology',
  'NEVOLYN Tech',
  'NEVOLYN Automation',
  'নেভোলিন',
  'নেভোলিন টেকনোলজি',
] as const

/** Comprehensive list of career, job vacancy, and recruitment search keywords */
export const NEVOLYN_CAREER_KEYWORDS = [
  // ── English Career & Job Search Queries ──
  'nevolyn career',
  'career nevolyn',
  'job nevolyn',
  'nevolyn job',
  'vacancy nevolyn',
  'nevolyn vacancy',
  'nevolyn vacancies',
  'nevolyn career search',
  'career search nevolyn',
  'nevolyn join us',
  'join us nevolyn',
  'join nevolyn',
  'nevolyn careers',
  'careers nevolyn',
  'nevolyn jobs',
  'jobs nevolyn',
  'nevolyn hiring',
  'hiring nevolyn',
  'nevolyn recruitment',
  'nevolyn job circular',
  'nevolyn circular',
  'nevolyn tech jobs',
  'nevolyn software engineer job',
  'nevolyn ai engineer job',
  'nevolyn automation engineer job',
  'nevolyn robotics engineer job',
  'nevolyn embedded systems job',
  'nevolyn full stack developer',
  'nevolyn technology careers',
  'nevolyn technology job vacancy',
  'nevolyn internship',
  'nevolyn careers bangladesh',
  'nevolyn jobs in dhaka',
  'nevolyn work with us',
  'apply to nevolyn',

  // ── FABINS Career & Job Search Queries (Connecting Product to NEVOLYN Careers) ──
  'fabins career',
  'fabins careers',
  'career fabins',
  'careers fabins',
  'join fabins',
  'fabins join us',
  'join us fabins',
  'fabins job',
  'fabins jobs',
  'job fabins',
  'jobs fabins',
  'fabins vacancy',
  'fabins vacancies',
  'vacancy fabins',
  'fabins career search',
  'fabins hiring',
  'fabins recruitment',
  'fabins job circular',
  'fabins internship',
  'fabins automation career',
  'fabins automation jobs',
  'fabins automation vacancy',
  'join fabins automation',
  'ফেবিন্স ক্যারিয়ার',
  'ফেবিন্স চাকরি',
  'ফেবিন্স জব',
  'ফেবিন্স নিয়োগ',
  'ফেবিন্স সার্কুলার',
  'ফেবিন্স ভ্যাকেন্সি',
  'ফেবিন্স জয়েন',

  // ── Bengali Script Career & Vacancy Variations ──
  'নেভোলিন ক্যারিয়ার',
  'নেভোলিন চাকরি',
  'নেভোলিন জব',
  'নেভোলিন নিয়োগ',
  'নেভোলিন সার্কুলার',
  'নেভোলিন ক্যারিয়ার সার্চ',
  'নেভোলিন ভ্যাকেন্সি',
  'নেভোলিন জয়েন আস',
] as const

/** Careers / Join Us page SEO configuration */
export const NEVOLYN_CAREERS_SEO = {
  title: 'Careers | NEVOLYN',
  description:
    'Explore NEVOLYN career opportunities, job vacancies, and engineering internships. Apply to join our deep-tech team building industrial robotics, AI systems, and automation software in Dhaka, Bangladesh.',
  keywords: [
    ...NEVOLYN_BRAND_ALIASES,
    ...NEVOLYN_CAREER_KEYWORDS,
  ],
} as const

export const NEVOLYN_SEO_CONFIG = {
  siteUrl: 'https://nevolyn.com',
  fabinsUrl: 'https://fabins.nevolyn.com',
  title: 'NEVOLYN',
  description:
    'NEVOLYN is an advanced engineering and deep-tech company building intelligent systems, applied AI, computer vision, and industrial automation platforms.',
  brandName: 'NEVOLYN Technology',
  productBrandName: 'FABINS Automation',
  social: {
    linkedin: 'https://www.linkedin.com/company/nevolyn/',
    fabinsLinkedin: 'https://www.linkedin.com/company/fabinsautomation/',
  },
  keywords: [
    // ── All NEVOLYN Brand, Typos & Transliterations ──
    ...NEVOLYN_BRAND_ALIASES,

    // ── Career & Job Search Queries ──
    ...NEVOLYN_CAREER_KEYWORDS,

    // ── Core Industry & Engineering Domains ──
    'Industrial Automation',
    'industrial automation',
    'Industrial Automation Solutions',
    'industrial automation solutions',
    'Industrial Automation Company',
    'industrial automation company',
    'Industrial Automation Bangladesh',
    'garments automation',
    'Garments Automation',
    'Garments Automation Bangladesh',
    'garment automation',
    'Garment Automation',
    'smarter automation',
    'Smarter Automation',
    'smarter ai automation',
    'Smarter AI Automation',
    'smarter aiurommation',
    'smarter manufacturing',
    'Smarter Manufacturing',
    'engineering solutions',
    'Engineering Solutions',
    'engineering solution',
    'Engineering Solution',
    'Advanced Engineering Solutions',
    'advanced engineering solutions',
    'Deep Tech Bangladesh',
    'Applied Artificial Intelligence',
    'Intelligent Systems',
    'Computer Vision Systems',
    'Edge AI & Embedded Systems',
    'Industrial Robotics',
    'Smart Factory Solutions',
    'Industry 4.0 Bangladesh',
    'Factory Automation',
    'Manufacturing Technology',
    'Automated Quality Control',
    'Optical Inspection Systems',
    'Industrial IoT & Telemetry',

    // ── Software Engineering & Enterprise Platforms ──
    'Enterprise Software Engineering',
    'Machine Learning Engineering',
    'High Performance Systems',
    'Spring Boot & Java Architectures',
    'Next.js & React Web Platforms',
    'Hardware & Embedded Development',

    // ── Product Context ──
    'Textile Automation Bangladesh',
    'RMG Automation Bangladesh',
    'Garment Inspection Automation',
    'Defect Detection System',
    'FABINS',
    'FABINS Automation',
    'Fabric Inspection Automation',
  ],
} as const

/**
 * Schema.org structured data (JSON-LD) establishing NEVOLYN as the parent organization
 * and FABINS as its product & subOrganization.
 */
export const nevolynJsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'Organization',
      '@id': `${NEVOLYN_SEO_CONFIG.siteUrl}/#organization`,
      name: 'NEVOLYN',
      alternateName: [...NEVOLYN_BRAND_ALIASES],
      url: `${NEVOLYN_SEO_CONFIG.siteUrl}/`,
      logo: `${NEVOLYN_SEO_CONFIG.siteUrl}/nevolyn-logo.png`,
      sameAs: [
        NEVOLYN_SEO_CONFIG.social.linkedin,
      ],
      contactPoint: {
        '@type': 'ContactPoint',
        email: 'info@nevolyn.com',
        contactType: 'customer support',
      },
      knowsAbout: [
        'Industrial Automation',
        'Industrial Automation Solutions',
        'Garments Automation',
        'Smarter Automation',
        'Smarter Manufacturing',
        'Engineering Solutions',
        'Deep Tech',
        'Artificial Intelligence',
        'Computer Vision',
        'Intelligent Systems',
        'Industrial Robotics',
        'Smart Manufacturing',
        'Fabric Inspection Automation',
        'Textile Automation Bangladesh',
        'RMG Automation',
      ],
      subOrganization: {
        '@type': 'Organization',
        '@id': `${NEVOLYN_SEO_CONFIG.fabinsUrl}/#organization`,
        name: 'FABINS Automation',
        url: `${NEVOLYN_SEO_CONFIG.fabinsUrl}/`,
      },
    },
    {
      '@type': ['Product', 'SoftwareApplication'],
      '@id': `${NEVOLYN_SEO_CONFIG.fabinsUrl}/#product`,
      name: 'FABINS Automation',
      alternateName: [
        'FABINS',
        'AI-Powered Fabric Inspection Automation',
      ],
      description:
        'AI-powered fabric inspection automation retrofit system developed by NEVOLYN for automated defect detection in textile and RMG mills.',
      url: `${NEVOLYN_SEO_CONFIG.fabinsUrl}/`,
      image: `${NEVOLYN_SEO_CONFIG.siteUrl}/nevolyn-image.png`,
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Linux, Windows, Web',
      manufacturer: {
        '@id': `${NEVOLYN_SEO_CONFIG.siteUrl}/#organization`,
      },
      offers: {
        '@type': 'Offer',
        price: '0',
        priceCurrency: 'USD',
        availability: 'https://schema.org/InStock',
        url: `${NEVOLYN_SEO_CONFIG.fabinsUrl}/`,
      },
    },
    {
      '@type': 'WebSite',
      '@id': `${NEVOLYN_SEO_CONFIG.siteUrl}/#website`,
      url: `${NEVOLYN_SEO_CONFIG.siteUrl}/`,
      name: 'NEVOLYN Technology',
      publisher: {
        '@id': `${NEVOLYN_SEO_CONFIG.siteUrl}/#organization`,
      },
    },
  ],
}
